### ISSUE TITLE
can i use this to create a toggle button in the top left

### ISSUE THREAD

**Issue by bendnuts** [DeltaNedas/ui-lib#10]
like the one in unitfactory, but toggleable, and without a menu it goes into? i like the way it goes into the topleft

**Comment by bendnuts** [comment]
![image](https://user-images.githubusercontent.com/70787919/160755710-2060d745-71c0-404c-ae0d-65c5cc466b1c.png)
its a bit.. low....

**Comment by bendnuts** [comment]
all the ones toward the right i added

**Comment by bendnuts** [comment]
oh i should probably get the v6 branch

**Comment by bendnuts** [comment]
nope, 6.0 is just worse

**Comment by DeltaNedas** [comment]
unit factory uses ui lib so just copy it

**Comment by bend-n** [comment]
> unit factory uses ui lib so just copy it

it cant toggle
