### ISSUE TITLE
139 crash on startup

### ISSUE THREAD

**Issue by SparkdotIe** [deltanedas/ui-lib#13]
there's not much more I can say than the title here, when using the UI-lib the game crashes on startup with an "index can't equal 1 >= 1"

here's the crash report
[crash-report-10_04_2022_17_58_57.txt](https://github.com/deltanedas/ui-lib/files/9711400/crash-report-10_04_2022_17_58_57.txt)

**Comment by YaeSakuraQvQ** [comment]
same issue
the same crash reason
fix it plz
in mindustry 139

**Comment by xmdnx** [comment]
same issue 139

**Comment by minombreesprorax** [comment]
dude, fix it

**Comment by Anuken** [comment]
v140 will have ui-lib blacklisted; I don't think this is getting fixed, and I don't want to deal with these kinds of problems in the future if any UI changes. The API in this mod should just be moved to the core game if it's necessary.

**Comment by deltanedas** [comment]
its fixed now
