### ISSUE TITLE
unsupported

### ISSUE THREAD

**Issue by niocresup** [deltanedas/ui-lib#14]
this modhas beenmanually blacklisted for causing crashes or othe issues with this version of the game. my ver: 140 (7.0)

**Comment by j-refs** [comment]
So how do I use this? RTFM  does not work without it, and I can't install this due to this issue. Should I rollback the game version? Or what can I do to get RTFM working

**Comment by minombreesprorax** [comment]
The lib is still **disabled**, not working, could you please fix it? I want to use some mods, and I do not want to go **v6**

**Comment by littelcat456** [comment]
well, you could just fork mindustry, remove ui-lib from [this](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/mod/Mods.java) file (remember to keep the quote marks in the brackets)
and then recompile

**Comment by nashviray** [comment]
Im so confused i don't know what im going to do

**Comment by ExcellentFisherman** [comment]
> well, you could just fork mindustry, remove ui-lib from [this](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/mod/Mods.java) file (remember to keep the quote marks in the brackets otherwise java probably won't like it) and then recompile

how do i recompile?

**Comment by Kepler-Gigaz** [comment]
I finally found how to bypass the Ui Lib.
Unfortunately it is complex for those who do not have minimal knowledge of programming.

Step 1:go to "/ > storage > emulated > 0 > android > data > io.anuken.mindustry > files > mods".

Step 2:unzip deltanedas-ui-lib.zip.

Step 3:rename libraries in "/ > storage > emulated > 0 > android > data > io.anuken.mindustry > files > mods > deltanedas-ui-lib > deltanedas-ui-lib-13c931a > scripts" the file where it is renamed is called "main.js" in code line 18.

Step 4:rename everything, but with the same inside "/ > storage > emulated > 0 > android > data > io.anuken.mindustry > files > mods > deltanedas-ui-lib > deltanedas-ui-lib-13c931a" a mod.json.

Step 5:copy "deltanedas-ui-lib-13c931a" (you must change the name except "-13c931a").

Step 6:stick it on "/ > storage > emulated > 0 > android > data > io.anuken.mindustry > files > mods" and zip it.

and ready! I already bypassed the file through the mindustry blacklist, the bad thing is that other mods won't be able to read it, if you want I tell you how :).


Or do I just give you a download link so that you can just move the files in the mods folder and not make life more complicated?.

**Comment by PixelProtogen** [comment]
> I finally found how to bypass the Ui Lib. Unfortunately it is complex for those who do not have minimal knowledge of programming.
> 
> Step 1:go to "/ > storage > emulated > 0 > android > data > io.anuken.mindustry > files > mods".
> 
> Step 2:unzip deltanedas-ui-lib.zip.
> 
> Step 3:rename libraries in "/ > storage > emulated > 0 > android > data > io.anuken.mindustry > files > mods > deltanedas-ui-lib > deltanedas-ui-lib-13c931a > scripts" the file where it is renamed is called "main.js" in code line 18.
> 
> Step 4:rename everything, but with the same inside "/ > storage > emulated > 0 > android > data > io.anuken.mindustry > files > mods > deltanedas-ui-lib > deltanedas-ui-lib-13c931a" a mod.json.
> 
> Step 5:copy "deltanedas-ui-lib-13c931a" (you must change the name except "-13c931a").
> 
> Step 6:stick it on "/ > storage > emulated > 0 > android > data > io.anuken.mindustry > files > mods" and zip it.
> 
> and ready! I already bypassed the file through the mindustry blacklist, the bad thing is that other mods won't be able to read it, if you want I tell you how :).
> 
> Or do I just give you a download link so that you can just move the files in the mods folder and not make life more complicated?.

Yes please

**Comment by nashviray** [comment]
how bout for pc 

> I finally found how to bypass the Ui Lib. Unfortunately it is complex for those who do not have minimal knowledge of programming.
> 
> Step 1:go to "/ > storage > emulated > 0 > android > data > io.anuken.mindustry > files > mods".
> 
> Step 2:unzip deltanedas-ui-lib.zip.
> 
> Step 3:rename libraries in "/ > storage > emulated > 0 > android > data > io.anuken.mindustry > files > mods > deltanedas-ui-lib > deltanedas-ui-lib-13c931a > scripts" the file where it is renamed is called "main.js" in code line 18.
> 
> Step 4:rename everything, but with the same inside "/ > storage > emulated > 0 > android > data > io.anuken.mindustry > files > mods > deltanedas-ui-lib > deltanedas-ui-lib-13c931a" a mod.json.
> 
> Step 5:copy "deltanedas-ui-lib-13c931a" (you must change the name except "-13c931a").
> 
> Step 6:stick it on "/ > storage > emulated > 0 > android > data > io.anuken.mindustry > files > mods" and zip it.
> 
> and ready! I already bypassed the file through the mindustry blacklist, the bad thing is that other mods won't be able to read it, if you want I tell you how :).
> 
> Or do I just give you a download link so that you can just move the files in the mods folder and not make life more complicated?.

How bout Pc users?

**Comment by Scamolor** [comment]
For Windows users, you do the same thing, except that the Mindustry mod folder is C:\Users\<username>\AppData\Roaming\Mindustry\mods.

For Linux or Mac users, I'm not sure where the Mindustry mod folder is

**Comment by minachiroshiwa** [comment]
I'm sorry,but this mod unsupported for Mindustry 7-offcial build 142
Reason is got into blacklist because get error for the game

**Comment by minachiroshiwa** [comment]
> I'm sorry,but this mod unsupported for Mindustry 7-offcial build 142
> Reason is got into blacklist because get error for the game

How I can use it on ver 142?

**Comment by Azzurous** [comment]
@Kepler-Gigaz got really close to the right answer here and it really helped me figure out the rest. All you have to do is follow the same steps as before but for both ui-lib and the mod that needs it as a dependency. Personally I just opened these mod.json/main.js files for both mods and did a replace-all on them. I kept it simple changing "ui-lib" to "ui-lib1" 

![image](https://user-images.githubusercontent.com/38433708/227509566-714eb584-62f6-4754-850f-9c37e835f8d9.png)

and in case the explanation of the file locations wasn't clear enough here's a visual for where to find them once you are **already in the mod folder**. Also the folders in the screen shot are the mod's .zip's after being extracted.

![image](https://user-images.githubusercontent.com/38433708/227511164-485fa86c-fb36-4644-8694-c199577101dd.png)

On pc you don't need to zip the folder again to have them work as a mod but I'm not sure if that required on the mobile versions of the game.

**Comment by deltanedas** [comment]
bozos just change the mod.json name

**Comment by mick-2006** [comment]
> bozos just change the mod.json name
how about you make a pr on the mindustry git and remove the blacklist on it ._.

**Comment by deltanedas** [comment]
check prs before you type, i already did
