### ISSUE TITLE
DeltaNeda's Mods Requires Ui-lib But Not Detected

### ISSUE THREAD

**Issue by Wharforklift** [deltanedas/ui-lib#21]
I have downloaded WAISA, PicToLogic, Tracker and more but they won't Recognize Ui Lib, I Have ui-lib installed in Mindustry and i kept reinstalling it but it didn't work, fix this!

**Comment by Wharforklift** [comment]
Mssing dependencies: Ui-lib

But i have Ui-lib installed

**Comment by deltanedas** [comment]
change ui-lib in depends to ui_lib i cbf
