### ISSUE TITLE
Crashes upon game launch

### ISSUE THREAD

**Issue by XEN0PHIL** [DeltaNedas/ui-lib#8]
**tl;dr:** rhino.EvaluatorException: Access to Java class "jdk.proxy2.$Proxy2" is prohibited.

**Platform:** Windows 7 x64
**Game version:** BE 20997
**UI Lib version:** 2.3.2
**JDK version:** 16 HotSpot
**Issue:** Mindustry crashes when launching it with UI Lib enabled.
**Crashlog:** [crash-report-04_03_2021_02_29_03.txt](https://github.com/DeltaNedas/ui-lib/files/6251621/crash-report-04_03_2021_02_29_03.txt)

**Comment by DeltaNedas** [comment]
on Debian Sid, openjdk-14-jre-headless and same versions of ui-lib and mindustry, it does not crash.
**consider using an older jre** as that smells like modern java being strange.
![Screenshot_02:20:30](https://user-images.githubusercontent.com/39013340/113495883-74efd700-94ec-11eb-81af-90103bde4926.png)
